name:                column-grep
version:             0.1.0.0
github:              "qualiaa/column-grep"
license:             BSD3
author:              "Jamie Bayne"
maintainer:          "jamiebayne@hotmail.com"
copyright:           "Jamie Bayne"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/qualiaa/column-grep#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- regex-base
- regex-pcre
- attoparsec
- word8

library:
  source-dirs: src

executables:
  column-grep-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - column-grep

tests:
  column-grep-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - column-grep
